### PR TITLE
Remove unwarranted gem dependencies

### PR DESCRIPTION
**Pull request by craiglittle**
In the end, these gems didn't provide enough value to justify the cost of the additional dependencies.

Inspired by: http://www.mikeperham.com/2016/02/09/kill-your-dependencies/

@zendesk/darko

### CODE REVIEW

**Comment by alex-stone** [comment]
Are you intending to make similar changes to Clavius w.r.t. `memoizable`?

**Comment by craiglittle** [comment]
> Are you intending to make similar changes to Clavius w.r.t. memoizable?

Yep, it's on the way! Stay tuned.

**Comment by craiglittle** [comment]
> > Are you intending to make similar changes to Clavius w.r.t. memoizable?

>Yep, it's on the way! Stay tuned.

`v1.0.2` of `clavius` [released](https://github.com/craiglittle/clavius/commits/master) with the dependency removed!

@alex-stone @joshlam :haircut: I've refactored the matchers a bit. This should be good to go.

**Comment by joshlam** [comment]
:+1:

**Pull request merged**
