### PR TITLE
Refactor "endnight DST" handling

### PR DESCRIPTION
**Pull request by craiglittle**
This includes a slight refactor of the recent fix for "endnight DST" time conversions as well as additional hardening and other refactoring for clarity. Check out the individual commits for more details.

@alex-stone 

/cc @zendesk/twrk

### CODE REVIEW

**Comment by alex-stone** [comment]
:+1:

**Comment by james2m** [comment]
Midnight seems an odd choice, it's incorrect for the vast majority of western countries. Isn't there a better way to spot the transition over a DST boundary?

**Comment by craiglittle** [comment]
Hey, @james2m. I don't think I follow. Is there a bug you're experiencing?

**Comment by james2m** [comment]
Yes, I was, but I can't re-create it easily as I had to pull Biz out just prior to this patch. I am scheduling time slots of 2 hours throughout the day and night and across US time zones, but because Biz Is handling DST at midnight I was getting loops and issues jumping back, and incorrect times after midnight. 

So what I was getting at was why midnight instead of when Ruby knows its crossed DST?

I'd give it a shot if I thought it didn't clash with your approach, so figured ask first.

**Comment by craiglittle** [comment]
I apologize if I remain a little confused as the DST logic at its core isn't based around midnight. Let me give you some context as to what this PR is doing and how we handle spring-forward DST adjustments in general.

Typically, when a user tries to create a non-existent spring-forward time (e.g. 2:30am in US time zones in the spring), we add one hour and try again. This is almost identical to [how Rails does it](https://github.com/rails/rails/blob/714ab8cb5976587470c8487720094c1efb2ba9a2/activesupport/lib/active_support/time_with_zone.rb#L477-L481).

This PR implements a fix for spring-forward DST in a very specific case, namely for time zones where the skipped time period includes the hour between 11pm and midnight. When creating a time in that segment of time on the spring-forward date, we were adding an hour's worth of seconds to the underlying "day time" object, which returned a nonsensical result. Instead, we needed the logic to "roll over" the adjusted date to the next day properly. That's what this PR does (or more specifically, refactors).

With that said, hopefully it's apparent that the fix in this PR is very niche and shouldn't affect time calculations in US time zones.

If you could provide a specific example or two of where you're getting suspect results, I'm happy to dig into it. Without something concrete, though, it's difficult for me to diagnose the issue.

**Comment by james2m** [comment]
Thanks Craig, when time permits I'll re-integrate Biz and see if I can reproduce. The errors/loops we were seeing were on leap back when scheduling Windows into the future and some of those leapt back from DST. 

Thanks for taking the time to reply in detail. Much appreciated. 

James

**Pull request merged**
