### PR TITLE
Add basic hours validations

### PR DESCRIPTION
**Pull request by craiglittle**
When configuring the gem, we'll now throw errors when the hours configuration:
  * is not hash-like.
  * does not contain any blocks of hours.

Resolves https://github.com/zendesk/biz/issues/31.

@alex-stone @kruppel @mfkp

### CODE REVIEW

**Comment by kruppel** [comment]
:+1:

**Comment by craiglittle** [comment]
Code Climate doesn't seem to want to do its job today.

**Comment by craiglittle** [comment]
Released in `v1.3.1`.

**Comment by mfkp** [comment]
:+1: thanks for the update

**Pull request merged**
